#!/bin/bash
#---------------------------------------------------------------
# Java Installation
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------
# Inspect the Manifest of the Container
#---------------------------------------------------------------

# Source the organization-wide config 
source ../utils/config-org.env
source utils/common-functions
source ../utils/colimaStatus

# Set version from $2
set_version "$2"

# Determine configuration based on $1
determine_config "$1"

echo "Inspect the Manifest of the container"
echo "skopeo inspect --raw docker://$ORG/$SERVICE "
skopeo inspect --raw docker://$ORG/$SERVICE
