#!/bin/bash
#---------------------------------------------------------------
# Java Installation
# Araf Karsh Hamid, (c) Copyright 2025
#
# Version 0.01
#---------------------------------------------------------------
# Push Java 21 Docker Container to Docker Hub
#---------------------------------------------------------------

# Source the organization-wide config 
source utils/config-org.env
source utils/common-functions

# Set version from $2
set_version "$2"

# Determine configuration based on $1
determine_config "$1"


echo "docker push $ORG/$SERVICE"
docker push $ORG/$SERVICE
