#!/bin/sh
# -------------------------------------------------------------------------------------------
# @author: Araf Karsh Hamid
# -------------------------------------------------------------------------------------------
# Developer Local Compile Process
# ===========================================================================================
# 1. Clean up the target folder
# 2. Generate the Build Number (from git commit count) and Build Date
# 3. Build the Service
# 4. Copy the jar file to the Lib Folder
# 5. Start the Service using ./run script and then test it with ./test script
#
# After the Successful build and Startup of the Service, It should show the Build No. & Date
# -------------------------------------------------------------------------------------------
SERVICE=`getServiceName`
CONTAINER=`getServiceName 4`
ORG=`getServiceName 1`
echo "---------------------------------------------------------------------------------------"
echo "1. Compiling $ORG/$SERVICE Microservice"
echo "---------------------------------------------------------------------------------------"
#echo "Changing Logback Log File Name: /tmp/$SERVICE-server.%d{yyyy-MM-dd}.%i.log"
#echo "---------------------------------------------------------------------------------------"
#sed -i -r "s/microservice/$SERVICE/g" src/main/resources/logback.xml
#sed -i -r "s/microservice/$SERVICE/g" src/main/resources/logback-test.xml
echo "Clean up the target folder: mvn clean"
echo "---------------------------------------------------------------------------------------"
mvn clean
# -------------------------------------------------------------------------------------------
echo "Git Commit Count = "`git rev-list HEAD --count`
echo "---------------------------------------------------------------------------------------"
generateBuildNumber $SERVICE
# -------------------------------------------------------------------------------------------
echo "2. Build the $ORG/$SERVICE Microservice : mvn -e package"
echo "---------------------------------------------------------------------------------------"
mvn -e package
mvnCompRV=$?
# -------------------------------------------------------------------------------------------
if [ $mvnCompRV == 0 ] 
then
	echo "---------------------------------------------------------------------------------------"
	echo "2.1 Compiling Service > $ORG/$SERVICE :: SUCCESS"
	echo "---------------------------------------------------------------------------------------"
	echo "2.2 Copy the Fat and Thin jar files and the libs to the Docker Directory (src/docker)"
	cp target/*service*-spring-boot.jar src/docker/Input/$CONTAINER-spring-boot.jar
	#cp target/*service*?.?.?.jar src/docker/Input/$CONTAINER-thin.jar
	#cp target/libs/* src/docker/libs/
	echo "2.3 Copy the application.properties File to the Docker Directory (src/docker)"
	cp src/main/resources/application.properties src/docker/Input
	cp src/main/resources/application-dev.properties src/docker/Input
	cp src/main/resources/application-staging.properties src/docker/Input
	cp src/main/resources/application-prod.properties src/docker/Input
	echo "2.4 Copy the application.properties Files to config directory."
	cp src/main/resources/application.properties config
	cp src/main/resources/application-dev.properties config
	cp src/main/resources/application-staging.properties config
	cp src/main/resources/application-prod.properties config
	echo "2.5 Copy the logback-spring xml Files to config directory."
	cp src/main/resources/logback-spring.xml config
	cp src/main/resources/logback-spring-scope.xml config
	cp src/main/resources/logback-spring-appenders-json.xml config
	cp src/main/resources/logback-spring-appenders-text.xml config
	cp src/main/resources/logback-spring-appenders-json-logstash.xml config
	echo "2.6 Copy the logback-spring xml Files to Docker directory src/docker/"
	cp src/main/resources/logback-spring.xml src/docker/Input
	cp src/main/resources/logback-spring-scope.xml src/docker/Input
	cp src/main/resources/logback-spring-appenders-text.xml src/docker/Input
	cp src/main/resources/logback-spring-appenders-json.xml src/docker/Input
	cp src/main/resources/logback-spring-appenders-json-logstash.xml src/docker/Input
	echo "---------------------------------------------------------------------------------------"
	echo "2.7. Building the Container for $ORG/$SERVICE Service ..... "
	echo "---------------------------------------------------------------------------------------"
	echo "2.7.1 Docker Build Process Disabled.... Run the build command separately"
	#build
	echo "---------------------------------------------------------------------------------------"
	echo "3. $SERVICE Microservice Build Process Completed Successfully! ........... "
	echo "---------------------------------------------------------------------------------------"
	echo "3.1 Start the Service using "
	echo "  run profile (dev, staging, prod) : Run the SpringBoot App  OR "
	echo "  startfg profile (dev, staging, prod) : Start docker container in foreground OR"
	echo "  start profile (dev, staging, prod) : Start the Container as a daemon)"
	echo "3.2 Then to test it with"
	echo "  test (To Test the SpringBoot App)"
	echo "---------------------------------------------------------------------------------------"
	echo "3.3 After the Successful build and Startup of the Service, It should show the Build No. & Date"
	echo "---------------------------------------------------------------------------------------"
else
	echo "---------------------------------------------------------------------------------------"
	echo "2.99 Compiling Service > $ORG/$SERVICE :: FAILED!!!"
	echo "---------------------------------------------------------------------------------------"
fi
