#!/bin/bash
# -------------------------------------------------------------------------------------------
# @author: Araf Karsh Hamid
# -------------------------------------------------------------------------------------------
# Developer Local Compile Process
# ===========================================================================================
# 1. Clean up the target folder
# 2. Generate the Build Number (from git commit count) and Build Date
# 3. Build the Service
# 4. Copy the jar file to the Lib Folder
# 5. Start the Service using ./run script and then test it with ./test script
#
# After the Successful build and Startup of the Service, It should show the Build No. & Date
# -------------------------------------------------------------------------------------------
SERVICE=`getServiceName`
CONTAINER=`getServiceName 4`
ORG=`getServiceName 1`
echo "---------------------------------------------------------------------------------------"
echo "1. Compiling $ORG/$SERVICE Microservice"
echo "---------------------------------------------------------------------------------------"
#echo "Changing Logback Log File Name: /tmp/$SERVICE-server.%d{yyyy-MM-dd}.%i.log"
#echo "---------------------------------------------------------------------------------------"
#sed -i -r "s/microservice/$SERVICE/g" src/main/resources/logback.xml
#sed -i -r "s/microservice/$SERVICE/g" src/main/resources/logback-test.xml
echo "Clean up the target folder: mvn clean"
echo "---------------------------------------------------------------------------------------"
mvn clean
# -------------------------------------------------------------------------------------------
echo "0. Git Commit Count = "`git rev-list HEAD --count`
echo "---------------------------------------------------------------------------------------"
generateBuildNumber $SERVICE
# -------------------------------------------------------------------------------------------
echo "2. Build the $ORG/$SERVICE Microservice : mvn -e package"
echo "---------------------------------------------------------------------------------------"
mvn -e package
mvnCompRV=$?
# -------------------------------------------------------------------------------------------
if [ $mvnCompRV == 0 ] 
then
	echo "---------------------------------------------------------------------------------------"
	echo "2.1 Compiling Service > $ORG/$SERVICE :: SUCCESS"
	echo "---------------------------------------------------------------------------------------"

	echo "2.2 Copy $CONTAINER-spring-boot.jar file to the Docker Directory (src/docker)"
	cp target/*service*-spring-boot.jar src/docker/Input/$CONTAINER-spring-boot.jar

	echo "2.3 Copy application.properties File to the Docker Directory (src/docker)"
	cp config/application*properties src/docker/Input

	echo "2.4 Copy application.properties File to the Kubernetes Directory (src/kubernetes)"
	convert4ConfigMap config/application.properties src/kubernetes/Package/dev/application.properties
	convert4ConfigMap config/application.properties src/kubernetes/Package/staging/application.properties
	convert4ConfigMap config/application.properties src/kubernetes/Package/prod/application.properties
	convert4ConfigMap config/application-dev.properties src/kubernetes/Package/dev/application-dev.properties
	convert4ConfigMap config/application-staging.properties src/kubernetes/Package/staging/application-staging.properties
	convert4ConfigMap config/application-prod.properties src/kubernetes/Package/prod/application-prod.properties

	source updateProperties

	echo "2.5 Copy logback-spring xml Files to config directory."
	cp src/main/resources/logback-spring*xml config

	echo "2.6 Copy logback-spring xml Files to Docker directory src/docker/"
	cp src/main/resources/logback-spring*xml src/docker/Input

	echo "---------------------------------------------------------------------------------------"
	echo "2.7. Building the Container for $ORG/$SERVICE Service ..... "
	echo "---------------------------------------------------------------------------------------"
	echo "2.7.1 Docker Build Process Disabled.... Run the build/buildx command separately"
	#build
	echo "---------------------------------------------------------------------------------------"
	echo "3. $SERVICE Microservice Build Process Completed Successfully! ........... "
	echo "---------------------------------------------------------------------------------------"
	echo "3.1 Start the Service using "
	echo "  run profile (dev, staging, prod) : Run the SpringBoot App  OR "
	echo "  startfg profile (dev, staging, prod) : Start docker container in foreground OR"
	echo "  start profile (dev, staging, prod) : Start the Container as a daemon)"
	echo "3.2 Then to test it with"
	echo "  test (To Test the SpringBoot App)"
	echo "---------------------------------------------------------------------------------------"
	echo "3.3 After the Successful build and Startup of the Service, It should show the Build No. & Date"
	echo "---------------------------------------------------------------------------------------"
else
	echo "---------------------------------------------------------------------------------------"
	echo "2.99 Compiling Service > $ORG/$SERVICE :: FAILED!!!"
	echo "---------------------------------------------------------------------------------------"
fi
