#!/bin/sh
# -------------------------------------------------------------------------------------------
# @author: Araf Karsh Hamid
# -------------------------------------------------------------------------------------------
SRC_BASE=${PWD}
orgName=1
serviceName=2
apiName=3
containerName=4
param=$1
if [ -z "$param" ]
then
	grep '^service.name=' $SRC_BASE/src/main/resources/app.props.tmpl |  cut -d "=" -f 2
	exit
fi
if [ $param == $orgName ] 
then
	grep '^service.org=' $SRC_BASE/src/main/resources/app.props.tmpl |  cut -d "=" -f 2
	exit
elif [ $param == $serviceName ]
then
	grep '^service.name=' $SRC_BASE/src/main/resources/app.props.tmpl |  cut -d "=" -f 2
	exit
elif [ $param == $apiName ] 
then
	grep '^service.api.name=' $SRC_BASE/src/main/resources/app.props.tmpl |  cut -d "=" -f 2
	exit
elif [ $param == $containerName ] 
then
	grep '^service.container=' $SRC_BASE/src/main/resources/app.props.tmpl |  cut -d "=" -f 2
	exit
fi
grep '^service.api.name=' $SRC_BASE/src/main/resources/app.props.tmpl |  cut -d "=" -f 2
exit
