#!/bin/bash
#---------------------------------------------------------------
# Base Alpine Installation
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

# Source the organization-wide config
source ../utils/config-org.env
source utils/common-functions
source ../utils/colimaStatus

determine_os "$1"

echo "docker push $ORG/$SERVICE"
docker push $ORG/$SERVICE
