#!/bin/bash
#---------------------------------------------------------------
# Base OS Installation
# Araf Karsh Hamid, (c) Copyright 2025
#
# Version 0.01
#---------------------------------------------------------------
# Shell Container
#---------------------------------------------------------------

# Source the organization-wide config
source utils/config-org.env
source utils/common-functions

determine_os "$1"

echo "docker container exec -it $ORG/$SERVICE /bin/bash"
docker container exec -it $ORG/$SERVICE /bin/bash
