#!/bin/bash
#---------------------------------------------------------------
# Base Alpine Installation
# Araf Karsh Hamid, (c) Copyright 2025
#
# Version 0.01
#---------------------------------------------------------------
# Stop Container
#---------------------------------------------------------------

# Source the organization-wide config
source utils/config-org.env
source utils/common-functions

determine_os "$1"

echo "docker container stop $ORG/$SERVICE"
docker container stop $ORG/$SERVICE
mv $SERVICE.cid $SERVICE.cid.old
