#!/bin/bash
#---------------------------------------------------------------
# Container Manager
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------
# Build Container
# --------------------------------------------------------------

# Get the Org Name, Service Name, Version and Full Container Name
cd ../../
source serviceName
source colimaStatus
cd src/docker
source utils/checkServiceJar

echo "Building Containr for $FULL_NAME "

# Build Container
echo "docker build --force-rm -f $DOCKER_FILE -t $FULL_NAME ."
docker build --force-rm -f $DOCKER_FILE -t $FULL_NAME .
