#!/bin/bash
#---------------------------------------------------------------
# Vanilla Microservice Container Manager
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0 
# Version 0.01
#---------------------------------------------------------------
# List all Docker Images
#---------------------------------------------------------------

# Check if Colima is running, if Not Start Colima
source utils/colimaStatus

echo "List all Docker images"
docker images
