#!/bin/bash
#---------------------------------------------------------------
# Server Installation
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------
# Remove Server Container Image
#---------------------------------------------------------------

# Source the organization-wide config
cd ../../
source serviceName
cd src/docker

# Check if Colima is running, if Not Start Colima
source utils/colimaStatus

echo "docker rmi $FULL_NAME"
docker rmi $FULL_NAME
