#!/bin/bash
#---------------------------------------------------------------
# Server Installation
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------
# Remove Server Container Image
#---------------------------------------------------------------

# Source the organization-wide config
cd ../../
source serviceName
cd src/docker

# Check if Colima is running, if Not Start Colima
source utils/colimaStatus
source utils/common-functions

# Set version from $2
set_version "$2"

# Determine os based on $1 and return the FULL_NAME
determine_os_java "$1" "$FULL_NAME"

echo "docker rmi $FULL_NAME"
docker rmi $FULL_NAME
