#!/bin/bash
#---------------------------------------------------------------
# Container Manager
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------
# Scan Container for Vulnerabilities
# --------------------------------------------------------------

# Get the Org Name, Service Name, Version and Full Container Name
cd ../../
source serviceName
source colimaStatus
cd src/docker

echo "Scanning $$FULL_NAME for vulnerabilities"
docker scan $$FULL_NAME
