#!/bin/bash
#---------------------------------------------------------------
# Vanilla Microservice Container Manager
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------
# Shell Container
# --------------------------------------------------------------

# Get the Org Name, Service Name, Version and Full Container Name
cd ../../
source serviceName
cd src/docker

# Check if Colima is running, if Not Start Colima
source utils/colimaStatus
source utils/common-functions

# Set version from $2
set_version "$2"

# Determine os based on $1 and return the FULL_NAME
determine_os_java "$1" "$FULL_NAME"

echo "docker container run -it $$FULL_NAME bash"
docker container run -it $$FULL_NAME bash
