#!/bin/bash
#---------------------------------------------------------------
# Vanilla Microservice Container Manager
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------
# Start Container
# --------------------------------------------------------------

# Get the Org Name, Service Name, Version and Full Container Name
cd ../../
source serviceName
cd src/docker

PORT=9334

# Check if Colima is running, if Not Start Colima
source utils/colimaStatus
source utils/common-functions

# Set version from $2
set_version "$2"

# Determine os based on $1 and return the FULL_NAME
determine_os_java "$1" "$FULL_NAME"

echo "docker container run --name $SERVICE -d --rm -p $PORT:9334 $$FULL_NAME"
docker container run --name $SERVICE -d --rm -p $PORT:9334 \
  -e JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD} \
  -e APP_PROFILE=$APP_PROFILE $$FULL_NAME

echo "Container id for $SERVICE ="`docker container ls | grep $SERVICE | tr -s " " | cut -d " " -f 1`
docker container ls | grep $SERVICE | tr -s " " | cut -d " " -f 1 > tmp/$SERVICE.cid
