#!/bin/bash
#---------------------------------------------------------------
# Vanilla Microservice Container Manager
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------
# Start Container in Foreground
# --------------------------------------------------------------

# Get the Org Name, Service Name, Version and Full Container Name
cd ../../
source serviceName
cd src/docker


PORT=9334
APP_PROFILE=$3

source utils/common-functions

# Set version from $2
set_version "$2"

# Determine os based on $1 and return the FULL_NAME
determine_os_java "$1" "$FULL_NAME"


# Check if Colima is running, if Not Start Colima
source utils/colimaStatus

#echo "Checkout API: http://localhost:$PORT/$API/api/v1/swagger-ui.html"
echo "docker container run -it --network="host" --name $SERVICE-$VERSION --rm -p $PORT:9334 \ "
	echo "-e JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD} \ "
	echo "-e APP_PROFILE=$APP_PROFILE \ "
	echo "-e SPRING_PROFILES_ACTIVE=$APP_PROFILE \ "
	echo "$FULL_NAME "

# Start the Container in Foreground
docker container run -it --network="host" --name $SERVICE-$VERSION --rm -p $PORT:9334 \
	-e JASYPT_ENCRYPTOR_PASSWORD=${JASYPT_ENCRYPTOR_PASSWORD} \
	-e APP_PROFILE=$APP_PROFILE \
	-e SPRING_PROFILES_ACTIVE=$APP_PROFILE \
	$FULL_NAME
