#---------------------------------------------------------------
# Java Installation
# Araf Karsh Hamid, (c) Copyright 2025
#
# Version 0.01
#---------------------------------------------------------------
# Java 11 Container
#---------------------------------------------------------------

FROM arafkarsh/ubuntu

# Metadata
LABEL maintainer="Araf Karsh Hamid <araf.karsh@gmail.com>" \
      description="This Dockerfile creates the Java Ubuntu image." \
      version="1.0" \
      org.opencontainers.image.authors="Araf Karsh Hamid <araf.karsh@gmail.com>" \
      org.opencontainers.image.version="1.0" \
      org.opencontainers.image.licenses="Apache 2"

RUN mkdir -p /Softwares/jdk11 

RUN apt-get install -y openjdk-11-jdk
    
# Copy the JDK 11 to Tmp directory
#COPY  jdk-11.0.25_linux-aarch64_bin.tar.gz /tmp/jdk11-arm.tar.gz

#RUN tar -xzf /tmp/jdk11-arm.tar.gz -C /Softwares/jdk11 --strip-components=1 && \
    #rm -f /tmp/jdk11-arm.tar.gz && \
    #chown -R ozazo:dev /Softwares/jdk11 && \
    #chmod -R 750 /Softwares/jdk11

# Add profile information to .bash_profile
RUN { \
    echo "echo \"----------------------------------------------------------------\""; \
    echo "java -version"; \
    echo "echo \"----------------------------------------------------------------\""; \
    echo "echo \"Ubuntu arm64/amd64 Java 11 Container\""; \
    echo "echo \"----------------------------------------------------------------\""; \
  } >> /home/ozazo/.bash_profile

#ENV PATH $PATH:/Softwares/jdk11/bin:
#ENV JAVA_HOME /Softwares/jdk11

# Enable User ozazo at this Level
USER ozazo

ENTRYPOINT ["/bin/bash", "--login"]
