#---------------------------------------------------------------
# Java Ubuntu x86 Installation
# Araf Karsh Hamid, (c) Copyright 2025
#
# Version 0.01
#---------------------------------------------------------------
# Java 11 Container
#---------------------------------------------------------------

FROM arafkarsh/ubuntu

MAINTAINER Araf Karsh Hamid "araf.karsh@gmail.com"

# Download and install Java (Intel version)
RUN mkdir -p /Softwares/jdk11 && \
    wget -q https://download.oracle.com/java/11/latest/jdk-11_linux-x64_bin.tar.gz -O /tmp/jdk11.tar.gz && \
    tar -xzf /tmp/jdk11.tar.gz -C /Softwares/jdk11 --strip-components=1 && \
    rm -f /tmp/jdk11.tar.gz

RUN chown -R ozazo:dev /Softwares/jdk11 && \
  chmod -R 750 /Softwares/jdk11

# Add profile information to .bash_profile
RUN { \
    echo "echo \"----------------------------------------------------------------\""; \
    echo "java -version"; \
    echo "echo \"----------------------------------------------------------------\""; \
    echo "echo \"Ubuntu x86 Java 11 Container\""; \
    echo "echo \"----------------------------------------------------------------\""; \
  }  >> /home/ozazo/.bash_profile

ENV PATH $PATH:/Softwares/jdk11/bin:
ENV JAVA_HOME /Softwares/jdk11

# Enable User ozazo at this Level
USER ozazo

ENTRYPOINT ["/bin/bash", "--login"]
