#!/bin/bash
#---------------------------------------------------------------
# Vanilla Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

echo "---------------------------------------------------------------"
echo "Build Vanilla Container for Kubernetes Cluster..."
../docker/buildk8s alpaquita 21
echo "---------------------------------------------------------------"
