#!/bin/bash
#---------------------------------------------------------------
# Vanilla Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source utils/colimaStatus

echo "Delete the deployment..."
echo " kubectl delete deployment $1"
kubectl delete deployment $1
