#!/bin/bash
#---------------------------------------------------------------
# Vanilla Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source utils/colimaStatus

echo "Deploy the App..."
kubectl create -f Yamls/vanilla-deploy.yaml
