#!/bin/bash
#---------------------------------------------------------------
# Vanilla Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source utils/colimaStatus

echo "List All Artifacts of Vanilla Service"

kubectl get configmaps -o wide
#kubectl get pods,deploy,svc,ing,hpa -A -o wide
kubectl get secrets,pods,deploy,svc,ing,hpa -o wide
