#!/bin/bash
#---------------------------------------------------------------
# Vanilla Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source utils/colimaStatus

podName=`kubectl get pods | awk 'NR>1 {print $1}'`

echo "Check the HW usage of the Pod=$podName"
kubectl top pod $podName --no-headers=false --sum=false
while true; do kubectl top pod $podName --no-headers=true --sum=false; sleep 3; done
