#!/bin/bash
#---------------------------------------------------------------
# Vanilla Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source utils/colimaStatus

echo "Deploy the Vanilla Service in Kubernetes cluster"
kubectl create -f Yamls/vanilla-secret.yaml
kubectl create -f Yamls/vanilla-deploy.yaml
kubectl create -f Yamls/vanilla-service.yaml
kubectl create -f Yamls/vanilla-ingress.yaml
