#!/bin/bash
#---------------------------------------------------------------
# Vanilla Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source utils/colimaStatus

echo "Create ConfigMap using Kustomize utility"
kubectl kustomize ./Package > Yamls/vanilla-configmap-profiles.yaml

echo "Apply ConfigMaps to Kubernetes Cluster"
kubectl apply -f Yamls/vanilla-configmap-active.yaml
kubectl apply -f Yamls/vanilla-configmap-profiles.yaml
