#!/bin/bash
#---------------------------------------------------------------
# Vanilla Microservice Kubernetes Utils
# Araf Karsh Hamid, (c) Copyright 2025
# License: Apache 2.0
# Version 0.01
#---------------------------------------------------------------

source ../utils/colimaStatus


# Function to handle uninstallation
uninstall() {
  echo "Proceeding with uninstallation..."
  echo "---------------------------------------------------------------"
  echo "UnInstall the Vanilla ConfigMaps from Kubernetes cluster"
  echo "---------------------------------------------------------------"
  kubectl delete configmap vanilla-configmap-active
  kubectl delete configmap vanilla-configmap-profiles
  echo "---------------------------------------------------------------"
  echo "UnInstall the Vanilla Secret from Kubernetes cluster"
  echo "---------------------------------------------------------------"
  kubectl delete secret vanilla-secret
  echo "---------------------------------------------------------------"
  echo "UnInstall the Vanilla Service/Deploy from Kubernetes cluster"
  echo "---------------------------------------------------------------"
  kubectl delete service vanilla-service
  kubectl delete service database-service
  kubectl delete deploy vanilla-deployment
  echo "---------------------------------------------------------------"
  echo "UnInstall the Vanilla Ingress from Kubernetes cluster"
  echo "---------------------------------------------------------------"
  kubectl delete ingress vanilla-ingress
  echo "---------------------------------------------------------------"
  echo "Vanilla Uninstallation complete!"
  echo "---------------------------------------------------------------"
}

# List all the Vanilla Services

echo "---------------------------------------------------------------"
echo "App Configuration and Secrets"
echo "---------------------------------------------------------------"
kubectl get configmaps -o wide
echo "---------------------------------------------------------------"
kubectl get secrets -o wide
echo "---------------------------------------------------------------"
echo "Pods / Deployments / Services"
echo "---------------------------------------------------------------"
kubectl get pods -o wide
echo "---------------------------------------------------------------"
kubectl get deploy -o wide
echo "---------------------------------------------------------------"
kubectl get svc -o wide
echo "---------------------------------------------------------------"
echo "Ingress / HPA"
echo "---------------------------------------------------------------"
kubectl get ing -o wide 
echo "---------------------------------------------------------------"
kubectl get hpa -o wide
echo "---------------------------------------------------------------"
echo 

# Ask the user the question
read -p "Do you want to uninstall Vanilla-Service? (yes/y or no/n): " response

# Normalize the input to lowercase for easy comparison
response=$(echo "$response" | tr '[:upper:]' '[:lower:]')

# Process the response
if [[ "$response" == "y" || "$response" == "yes" ]]; then
  uninstall
elif [[ "$response" == "n" || "$response" == "no" ]]; then
  echo "Uninstallation canceled. Exiting."
else
  echo "Invalid input. Please enter yes/y or no/n."
fi

